changed tempfile location to a directory, and clean up directory on exit and interrupt

diff --git a/lextest b/lextest
--- a/lextest
+++ b/lextest
@@ -1,21 +1,22 @@
 #!/bin/bash
 
-rm failedfilestemp
+mkdir test_temp
+trap "{ rm -rf test_temp }" EXIT
+
 make
 
 test ()
 {
   echo "Testing: $1"
-  ./grun antlr.WACC program "$1" > testtemp 2>&1;
-  if [[ ($2 == "-valid" ) && ("$(cat testtemp)" != "running the ANTLR TestRig grammar tool") ]]; then
+  ./grun antlr.WACC program "$1" > test_temp/output 2>&1;
+  if [[ ($2 == "-valid" ) && ("$(cat test_temp/output)" != "running the ANTLR TestRig grammar tool") ]]; then
     echo "TEST FAILURE:"
-    echo "Test had the following output: $(cat testtemp)"
-    echo "$1" >> failedfilestemp;
+    echo "Test had the following output: $(cat test_temp/output)"
+    echo "$1" >> test_temp/failedfilestemp
   elif [[ ($2 == "-invalid") && ("$(cat testtemp)" == "running the ANTLR TestRig grammar tool") ]]; then
     echo "TEST UNEXPECTEDLY SUCCEEDED: $1"
-    echo "$1" >> failedfilestemp;
+    echo "$1" >> test_temp/failedfilestemp
   fi
-  rm testtemp
 }
 
 export -f test
@@ -25,12 +26,14 @@ find testcases/invalid -type f -iname '*.wacc' -exec bash -c 'test "$1" -invalid
 
 unset test
 
-if [ -f /failedfilestemp ] ; then
+if [ -f test_temp/failedfilestemp ] ; then
   echo "All tests passed..."
+  rm -rf failedfilestemp
   exit 0
 else
   echo "The following files failed the tests: "
   cat failedfilestemp
   rm failedfilestemp
+  rm -rf failedfilestemp
   exit 1
 fi
